from __future__ import annotations

from pydantic import BaseModel, Field


class ClientOutput(BaseModel):
    """Client information for the generated quote."""

    name: str | None = Field(default=None, description="Nombre del cliente")
    company: str | None = Field(default=None, description="Empresa del cliente")


class ProjectOutput(BaseModel):
    """Project metadata for the generated quote."""

    title: str = Field(description="Titulo del proyecto")
    subtitle: str | None = Field(default=None, description="Subtitulo o descripcion corta")


class DetailedFeatureOutput(BaseModel):
    """A detailed feature within a scope block."""

    title: str = Field(description="Nombre de la feature")
    description: str | None = Field(default=None, description="Descripcion de la feature")


class ScopeBlockOutput(BaseModel):
    """A functional scope block in the generated quote."""

    title: str = Field(description="Titulo del bloque funcional")
    short_description: str = Field(description="Descripcion corta del bloque")
    long_description: str | None = Field(
        default=None, description="Descripcion detallada del bloque"
    )
    features: list[str] = Field(
        default_factory=list,
        description="Lista de features incluidas en el bloque",
    )
    technologies: list[str] = Field(
        default_factory=list,
        description="Tecnologias utilizadas en este bloque",
    )
    detailed_features: list[DetailedFeatureOutput] = Field(
        default_factory=list,
        description="Features detalladas con titulo y descripcion",
    )


class RoadmapPhaseOutput(BaseModel):
    """A project phase in the roadmap."""

    name: str = Field(description="Nombre de la fase")
    duration: str | None = Field(
        default=None, description="Duracion estimada, e.g. '4 semanas'"
    )
    description: str | None = Field(default=None, description="Descripcion de la fase")
    deliverables: list[str] = Field(
        default_factory=list,
        description="Entregables de la fase",
    )
    modules: list[str] = Field(
        default_factory=list,
        description="Modulos funcionales incluidos en esta fase",
    )


class ItemOutput(BaseModel):
    """A line item (task) in the generated quote."""

    type: str = Field(
        default="service",
        description="Tipo de item: service, product, license",
    )
    name: str = Field(description="Nombre de la tarea")
    description: str | None = Field(default=None, description="Descripcion de la tarea")
    quantity: float = Field(description="Cantidad (dias, horas, etc.)", gt=0)
    unit: str = Field(default="dia", description="Unidad: dia, hora, mes, etc.")
    unit_price: float = Field(description="Precio unitario", gt=0)
    discount_percent: float = Field(
        default=0, description="Porcentaje de descuento", ge=0, le=100
    )
    phase: str | None = Field(
        default=None,
        description="Fase del roadmap a la que pertenece esta tarea",
    )


class TeamMemberOutput(BaseModel):
    """A team member profile for the project."""

    profile_type: str = Field(description="Tipo de perfil: frontend, backend, PM, etc.")
    description: str | None = Field(default=None, description="Descripcion del rol")
    quantity: int = Field(default=1, description="Numero de personas", ge=1)
    dedication: str = Field(
        default="full_time", description="Dedicacion: full_time o part_time"
    )


class ConditionsOutput(BaseModel):
    """Payment and service conditions."""

    payment_terms: list[str] = Field(
        default_factory=list,
        description="Condiciones de pago",
    )
    included_services: list[str] = Field(
        default_factory=list,
        description="Servicios incluidos",
    )


class QuoteOutput(BaseModel):
    """
    Complete quote output generated by the LLM pipeline.

    Mirrors the structure of QuoteInput for compatibility with the ingestion
    pipeline, but uses relaxed validators suitable for LLM generation via
    OpenAI Structured Output.
    """

    client: ClientOutput | None = Field(
        default=None, description="Informacion del cliente"
    )
    project: ProjectOutput = Field(description="Informacion del proyecto")
    currency: str = Field(default="EUR", description="Moneda del presupuesto (ISO 4217)")
    scope_blocks: list[ScopeBlockOutput] = Field(
        description="Bloques funcionales del proyecto (minimo 4, incluyendo exploracion/diseno)",
        min_length=4,
    )
    roadmap_phases: list[RoadmapPhaseOutput] = Field(
        description="Fases del roadmap del proyecto (minimo 3)",
        min_length=3,
    )
    items: list[ItemOutput] = Field(
        description="Tareas desglosadas del presupuesto (minimo 10)",
        min_length=10,
    )
    team_members: list[TeamMemberOutput] = Field(
        default_factory=list,
        description="Miembros del equipo propuesto",
    )
    conditions: ConditionsOutput | None = Field(
        default=None, description="Condiciones de pago y servicios"
    )
    notes: str | None = Field(
        default=None, description="Notas adicionales sobre el presupuesto"
    )
